import './LoaderStyles.scss'
export const Loader = () => {
  return (
    <div className="loader rainbow">
      <div className="circle" style={{'--i': '1'} as any}></div>
      <div className="circle" style={{'--i': '2'} as any}></div>
      <div className="circle" style={{'--i': '3'} as any}></div>
      <div className="circle" style={{'--i': '4'} as any}></div>
      <div className="circle" style={{'--i': '5'} as any}></div>
      <div className="circle" style={{'--i': '6'} as any}></div>
      <div className="circle" style={{'--i': '7'} as any}></div>
      <div className="circle" style={{'--i': '8'} as any}></div>
      <div className="circle" style={{'--i': '9'} as any}></div>
      <div className="circle" style={{'--i': '10'} as any}></div>
      <div className="circle" style={{'--i': '11'} as any}></div>
      <div className="circle" style={{'--i': '12'} as any}></div>
      <div className="circle" style={{'--i': '13'} as any}></div>
      <div className="circle" style={{'--i': '14'} as any}></div>
      <div className="circle" style={{'--i': '15'} as any}></div>
      <div className="circle" style={{'--i': '16'} as any}></div>
      <div className="circle" style={{'--i': '17'} as any}></div>
      <div className="circle" style={{'--i': '18'} as any}></div>
      <div className="circle" style={{'--i': '19'} as any}></div>
      <div className="circle" style={{'--i': '20'} as any}></div>
      <div className="circle" style={{'--i': '21'} as any}></div>
      <div className="circle" style={{'--i': '22'} as any}></div>
      <div className="circle" style={{'--i': '23'} as any}></div>
      <div className="circle" style={{'--i': '24'} as any}></div>
      <div className="circle" style={{'--i': '25'} as any}></div>
      <div className="circle" style={{'--i': '26'} as any}></div>
      <div className="circle" style={{'--i': '27'} as any}></div>
      <div className="circle" style={{'--i': '28'} as any}></div>
      <div className="circle" style={{'--i': '29'} as any}></div>
      <div className="circle" style={{'--i': '30'} as any}></div>
      <div className="circle" style={{'--i': '31'} as any}></div>
      <div className="circle" style={{'--i': '32'} as any}></div>
      <div className="circle" style={{'--i': '33'} as any}></div>
      <div className="circle" style={{'--i': '34'} as any}></div>
      <div className="circle" style={{'--i': '35'} as any}></div>
      <div className="circle" style={{'--i': '36'} as any}></div>
      <div className="circle" style={{'--i': '37'} as any}></div>
      <div className="circle" style={{'--i': '38'} as any}></div>
      <div className="circle" style={{'--i': '39'} as any}></div>
      <div className="circle" style={{'--i': '40'} as any}></div>
      <div className="circle" style={{'--i': '41'} as any}></div>
      <div className="circle" style={{'--i': '42'} as any}></div>
      <div className="circle" style={{'--i': '43'} as any}></div>
      <div className="circle" style={{'--i': '44'} as any}></div>
      <div className="circle" style={{'--i': '45'} as any}></div>
      <div className="circle" style={{'--i': '46'} as any}></div>
      <div className="circle" style={{'--i': '47'} as any}></div>
      <div className="circle" style={{'--i': '48'} as any}></div>
      <div className="circle" style={{'--i': '49'} as any}></div>
      <div className="circle" style={{'--i': '50'} as any}></div>
      <div className="circle" style={{'--i': '51'} as any}></div>
      <div className="circle" style={{'--i': '52'} as any}></div>
      <div className="circle" style={{'--i': '53'} as any}></div>
      <div className="circle" style={{'--i': '54'} as any}></div>
      <div className="circle" style={{'--i': '55'} as any}></div>
      <div className="circle" style={{'--i': '56'} as any}></div>
      <div className="circle" style={{'--i': '57'} as any}></div>
      <div className="circle" style={{'--i': '58'} as any}></div>
      <div className="circle" style={{'--i': '59'} as any}></div>
      <div className="circle" style={{'--i': '60'} as any}></div>
      <div className="circle" style={{'--i': '61'} as any}></div>
      <div className="circle" style={{'--i': '62'} as any}></div>
      <div className="circle" style={{'--i': '63'} as any}></div>
      <div className="circle" style={{'--i': '64'} as any}></div>
      <div className="circle" style={{'--i': '65'} as any}></div>
      <div className="circle" style={{'--i': '66'} as any}></div>
      <div className="circle" style={{'--i': '67'} as any}></div>
      <div className="circle" style={{'--i': '68'} as any}></div>
      <div className="circle" style={{'--i': '69'} as any}></div>
      <div className="circle" style={{'--i': '70'} as any}></div>
      <div className="circle" style={{'--i': '71'} as any}></div>
      <div className="circle" style={{'--i': '72'} as any}></div>
      <div className="circle" style={{'--i': '73'} as any}></div>
      <div className="circle" style={{'--i': '74'} as any}></div>
      <div className="circle" style={{'--i': '75'} as any}></div>
      <div className="circle" style={{'--i': '76'} as any}></div>
      <div className="circle" style={{'--i': '77'} as any}></div>
      <div className="circle" style={{'--i': '78'} as any}></div>
      <div className="circle" style={{'--i': '79'} as any}></div>
      <div className="circle" style={{'--i': '80'} as any}></div>
      <div className="circle" style={{'--i': '81'} as any}></div>
      <div className="circle" style={{'--i': '82'} as any}></div>
      <div className="circle" style={{'--i': '83'} as any}></div>
      <div className="circle" style={{'--i': '84'} as any}></div>
      <div className="circle" style={{'--i': '85'} as any}></div>
      <div className="circle" style={{'--i': '86'} as any}></div>
      <div className="circle" style={{'--i': '87'} as any}></div>
      <div className="circle" style={{'--i': '88'} as any}></div>
      <div className="circle" style={{'--i': '89'} as any}></div>
      <div className="circle" style={{'--i': '90'} as any}></div>
      <div className="circle" style={{'--i': '91'} as any}></div>
      <div className="circle" style={{'--i': '92'} as any}></div>
      <div className="circle" style={{'--i': '93'} as any}></div>
      <div className="circle" style={{'--i': '94'} as any}></div>
      <div className="circle" style={{'--i': '95'} as any}></div>
      <div className="circle" style={{'--i': '96'} as any}></div>
      <div className="circle" style={{'--i': '97'} as any}></div>
      <div className="circle" style={{'--i': '98'} as any}></div>
      <div className="circle" style={{'--i': '99'} as any}></div>
      <div className="circle" style={{'--i': '100 '} as any}></div>
    </div>
  )
}
